GET https://664b86f135bbda10987d4329.mockapi.io/contacts/14
###
PUT https://664b86f135bbda10987d4329.mockapi.io/contacts/11
Content-Type: application/json

{
  "createdAt": 1717324915,
  "name": "Wendy Mertz",
  "phone": "325-653-6694",
  "id": "3"
}
###
POST https://664b86f135bbda10987d4329.mockapi.io/contacts

###
DELETE https://664b86f135bbda10987d4329.mockapi.io/contacts/10
