GET https://connections-api.goit.global/contacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjUyYjg4OTkwZTBiODAwMTQwMjQwNzUiLCJpYXQiOjE3MjI1MDE2Njd9.FwqLRKH70WePjPDQPed6bkZTg9EpQBb6fuYCFHQpGVw

# [
#   {
#     "id": "66aa0a6bc495ed6e25f311a6",
#     "name": "Wendy Mertz",
#     "number": "325-653-6694"
#   }
# ]
###
POST https://connections-api.goit.global/users/login
Content-Type: application/json

{
  "email": "a.cross1@gmail.com",
  "password": "examplepwd12345"
}

# {
#   "user": {
#     "name": "Adrian Cross",
#     "email": "a.cross1@gmail.com"
#   },
#   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjUyYjg4OTkwZTBiODAwMTQwMjQwNzUiLCJpYXQiOjE3MjI1MDE2Njd9.FwqLRKH70WePjPDQPed6bkZTg9EpQBb6fuYCFHQpGVw"
# }
###

GET https://connections-api.goit.global/users/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjUyYjg4OTkwZTBiODAwMTQwMjQwNzUiLCJpYXQiOjE3MjI1MDE2Njd9.FwqLRKH70WePjPDQPed6bkZTg9EpQBb6fuYCFHQpGVw

# {
#   "name": "Adrian Cross",
#   "email": "a.cross1@gmail.com"
# }
###
POST https://connections-api.goit.global/contacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjUyYjg4OTkwZTBiODAwMTQwMjQwNzUiLCJpYXQiOjE3MjI1MDE2Njd9.FwqLRKH70WePjPDQPed6bkZTg9EpQBb6fuYCFHQpGVw
Content-Type: application/json

{
  "name": "Wendy Mertz1",
  "number": "325-653-6694"
}
###
